import Header from "@/components/header";
import GroupService from "@/services/GroupService";
import { Group } from "@/types";
import Head from "next/head";
import GroupOverviewTable from "@/components/groups/groupOverviewTable";
import { useEffect, useState } from "react";
import { User } from "@/types";
import UserOverviewTable from "@/components/users/UserOverviewTable";

const Groups: React.FC = () => {
    const [groups, setGroups] = useState<Array<Group>>([]);
    const [users, setUsers] = useState<Array<User>>([]);
    const [groupClicked, setGroupClicked] = useState<boolean>(false); 
    const getGroups = async () => {
        const response = await GroupService.getAllGroups();
        const json = await response.json();
        setGroups(json);
    };

    const getUsersByGroup = async (code: string) => {
        const response = await GroupService.getUsersByGroup(code);
        const json = await response.json();
        setUsers(json);
        setGroupClicked(true);
    };

    const handleRowClick = (groupCode: string) => {
        getUsersByGroup(groupCode); 
    };

    useEffect(() => {
        getGroups();
        setUsers([]); 
    }, []);

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Header />
                <h1>Groups:</h1>
                {groups && <GroupOverviewTable groups={groups} onRowClick={handleRowClick} />}

                {groupClicked && ( 
                    <>
                        <h1>Users:</h1>
                        {users.length > 0 ? ( 
                            <UserOverviewTable users={users} />
                        ) : (
                            <p className="missing-users-message">No users yet.</p> 
                        )}
                    </>
                )}
            </main>
        </>
    );
};

export default Groups;
