import Header from "@/components/header";
import GroupService from "@/services/GroupService";
import { Group } from "@/types";
import Head from "next/head";
import GroupOverviewTable from "@/components/groups/groupOverviewTable";
import { useEffect, useState } from "react";

const Groups: React.FC = () => {
    const [groups, setGroups] = useState<Array<Group>>([])

    const getGroups = async () => {
        const response = await GroupService.getAllGroups();
        const json = await response.json();
        setGroups(json)
    }

    useEffect(() => {
        getGroups();
    }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <h1>Groups:</h1>
        {groups && <GroupOverviewTable groups={groups}/>}
      </main>
    </>
  );
};

export default Groups;
